In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split

In [3]:
#import csv file
df = pd.read_csv("BTC.csv")
df

           Date    Price     Open     High      Low     Vol  Change
0     5/18/2018   8245.7   8064.4   8273.6   7939.8  150320  0.0227
1     5/19/2018   8245.1   8244.7   8389.1   8153.2  107890 -0.0001
2     5/20/2018   8529.0   8243.9   8580.4   8184.7  113760  0.0344
3     5/21/2018   8403.3   8529.5   8550.6   8375.5  115520 -0.0147
4     5/22/2018   8006.0   8403.8   8414.5   7979.3  137510 -0.0473
...         ...      ...      ...      ...      ...     ...     ...
1822  5/14/2023  26920.0  26777.4  27176.1  26609.9   26350  0.0053
1823  5/15/2023  27183.9  26920.4  27651.7  26752.1   53270  0.0098
1824  5/16/2023  27035.3  27183.9  27295.3  26881.9   45290 -0.0055
1825  5/17/2023  27403.1  27035.5  27465.3  26597.7   58140  0.0136
1826  5/18/2023  26828.0  27403.8  27467.0  26449.8   63390 -0.0210

[1827 rows x 7 columns]

In [4]:
# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set 'Date' as the index
df.set_index('Date', inplace=True)

# Create the target variable
y = df['Price']

# Create the feature matrix
X = df.drop('Price', axis=1)

In [5]:
# Split the dataset into train, test, and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.33, random_state=42)

In [6]:
# Initialize the Random Forest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [7]:
# Make predictions on the test set
y_pred_test = rf_model.predict(X_test)

# Calculate RMSE, MAE, and MAPE on the test set
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
mae_test = mean_absolute_error(y_test, y_pred_test)
mape_test = np.mean(np.abs((y_test - y_pred_test) / y_test)) * 100

# Make predictions on the validation set
y_pred_val = rf_model.predict(X_val)

# Calculate RMSE, MAE, and MAPE on the validation set
rmse_val = np.sqrt(mean_squared_error(y_val, y_pred_val))
mae_val = mean_absolute_error(y_val, y_pred_val)
mape_val = np.mean(np.abs((y_val - y_pred_val) / y_val)) * 100

# Print the evaluation metrics
print(f"Test set - RMSE: {rmse_test:.2f}, MAE: {mae_test:.2f}, MAPE: {mape_test:.2f}%")
print(f"Validation set - RMSE: {rmse_val:.2f}, MAE: {mae_val:.2f}, MAPE: {mape_val:.2f}%")

Test set - RMSE: 495.55, MAE: 249.76, MAPE: 1.08%
Validation set - RMSE: 433.21, MAE: 236.56, MAPE: 1.02%